Update action to not fail if it should just exit, exit 78 does not work.

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -119,124 +119,147 @@ runs:
       run: |
         if ($Env:HasUpgrade -ne "True") {
           echo "::warning::No upgrade detected"
-          exit 78
+          echo ("ActionContinue='false') >> $Env:GITHUB_ENV
         }
-
-        if ($Env:INPUT_DISABLE_UPGRADE_STEP -eq "true") {
+        elseif ($Env:INPUT_DISABLE_UPGRADE_STEP -eq "true") {
           echo "::warning::Upgrade step is disabled. Quitting."
-          exit 78
-        }
-
-        $branchName = "${{ inputs.package-name }}-upgrade-${{ env.CurrentVersion }}-to-${{ env.LatestVersion }}"        
-
-        git show-ref --verify --quiet `"refs/heads/$branchName`"
-        if ($?){
-          echo "Branch $branchName already exists, updating to branch"
-          git checkout "$branchName"
+          echo ("ActionContinue='false') >> $Env:GITHUB_ENV
         }
         else {
-          git branch "$branchName"
-          git checkout "$branchName"
-        }
+          $branchName = "${{ inputs.package-name }}-upgrade-${{ env.CurrentVersion }}-to-${{ env.LatestVersion }}"        
 
-        # set the variables
-        echo ("BranchName=" + $branchName) >> $Env:GITHUB_ENV
+          git show-ref --verify --quiet `"refs/heads/$branchName`"
+          if ($?){
+            echo "Branch $branchName already exists, updating to branch"
+            git checkout "$branchName"
+          }
+          else {
+            git branch "$branchName"
+            git checkout "$branchName"
+          }
+
+          # set the variables
+          echo ("BranchName=" + $branchName) >> $Env:GITHUB_ENV
+          echo ("ActionContinue='true') >> $Env:GITHUB_ENV
+        }
       shell: pwsh
       
     - name: Upgrading project
       run: |
-        $VerbosePreference = ($Env:INPUT_VERBOSE -eq "true") ? "Continue" : "SilentlyContinue"
-        
-        echo "::group::Running Nuget update for package ${{ inputs.package-name }}"
-        
-        $repoRoot = Get-Item "${{ github.workspace }}"
-        # don't specify explicit version, have nuget just update to the latest compatible
-        Update-NugetPackage -PackageName ${{ inputs.package-name }} -ProjectFile ${{ inputs.project-file}} -RootGitDirectory $($repoRoot.FullName) -NugetExe (Get-Command nuget).Source
+        $actionContinue = "${{ env.BranchName }}"
+        if ($actionContinue -eq 'true') {
+          $VerbosePreference = ($Env:INPUT_VERBOSE -eq "true") ? "Continue" : "SilentlyContinue"
+          
+          echo "::group::Running Nuget update for package ${{ inputs.package-name }}"
+          
+          $repoRoot = Get-Item "${{ github.workspace }}"
+          # don't specify explicit version, have nuget just update to the latest compatible
+          Update-NugetPackage -PackageName ${{ inputs.package-name }} -ProjectFile ${{ inputs.project-file}} -RootGitDirectory $($repoRoot.FullName) -NugetExe (Get-Command nuget).Source
 
-        echo "::endgroup::"
+          echo "::endgroup::"
+        }
       shell: pwsh
 
     - name: Building project
       working-directory: ${{ github.workspace }}
       run: |
-        echo "::group::Building the project ${{ inputs.project-file}}"
-        & msbuild ${{ inputs.project-file}}
-        echo "::endgroup::"
+        $actionContinue = "${{ env.BranchName }}"
+        if ($actionContinue -eq 'true') {
+          echo "::group::Building the project ${{ inputs.project-file}}"
+          & msbuild ${{ inputs.project-file}}
+          echo "::endgroup::"
+        }        
       shell: pwsh
 
     - name: Renaming Branch
       run: |
-        $actualVersion = Get-ConfigPackageVersion -PackageFile ${{ inputs.package-file }} -PackageName ${{ inputs.package-name }}
-        $branchName = "${{ inputs.package-name }}-upgrade-${{ env.CurrentVersion }}-to-$actualVersion"
-        
-        if ($actualVersion -ne $Env:LatestVersion) {
-          echo "Upgrade successful but could not auto upgrade to the latest $Env:LatestVersion version, Nuget could only resolve dependencies for version $actualVersion"
-        }
+        $actionContinue = "${{ env.BranchName }}"
+        if ($actionContinue -eq 'true') {
+          $actualVersion = Get-ConfigPackageVersion -PackageFile ${{ inputs.package-file }} -PackageName ${{ inputs.package-name }}
+          $branchName = "${{ inputs.package-name }}-upgrade-${{ env.CurrentVersion }}-to-$actualVersion"
+          
+          if ($actualVersion -ne $Env:LatestVersion) {
+            echo "Upgrade successful but could not auto upgrade to the latest $Env:LatestVersion version, Nuget could only resolve dependencies for version $actualVersion"
+          }
 
-        # rename the branch to the actual version
-        git branch -m $branchName
-        
-        # set the variables
-        echo ("ActualVersion=" + $actualVersion) >> $Env:GITHUB_ENV
-        echo ("BranchName=" + $branchName) >> $Env:GITHUB_ENV
+          # rename the branch to the actual version
+          git branch -m $branchName
+          
+          # set the variables
+          echo ("ActualVersion=" + $actualVersion) >> $Env:GITHUB_ENV
+          echo ("BranchName=" + $branchName) >> $Env:GITHUB_ENV
+        }        
       shell: pwsh
     
     - name: Committing changes
       run: |
         if ($Env:INPUT_DISABLE_COMMIT -eq "true") {
           echo "::warning::Commit step is disabled. Quitting."
-          exit 78
+          echo ("ActionContinue='false') >> $Env:GITHUB_ENV
         }
-
-        echo "::group::Committing changes"
-        $message = "Updated files for the ${{ inputs.package-name }} from ${{ env.CurrentVersion }} to ${{ env.ActualVersion }} (Attempted ${{ env.LatestVersion }} )"
-        git add -A
-        git -c "user.name=${{ inputs.git-bot-user }}" -c "user.email=${{ inputs.git-bot-email }}" commit -am "$message" --author "${{ inputs.git-bot-user }} <${{ env.GitBotEmail }}>"
-        echo "::endgroup::"
+        else {
+          echo "::group::Committing changes"
+          $message = "Updated files for the ${{ inputs.package-name }} from ${{ env.CurrentVersion }} to ${{ env.ActualVersion }} (Attempted ${{ env.LatestVersion }} )"
+          git add -A
+          git -c "user.name=${{ inputs.git-bot-user }}" -c "user.email=${{ inputs.git-bot-email }}" commit -am "$message" --author "${{ inputs.git-bot-user }} <${{ env.GitBotEmail }}>"
+          echo "::endgroup::"
+        }        
       shell: pwsh
 
     - name: Check for existing PR
       run: |
-        $VerbosePreference = ($Env:INPUT_VERBOSE -eq "true") ? "Continue" : "SilentlyContinue"
-        
-        echo "::group::Checking for existing Pull Request"
-        
-        $ghRepoParts = "${{ github.repository }}".Split("/")
-        $pr = Get-PullRequest -OwnerName $ghRepoParts[0] -RepositoryName $ghRepoParts[1] -AccessToken ${{ inputs.github-token }} -BranchName ${{ env.BranchName }}
-        
-        if ($pr) {
-          echo "::error::A Pull Request already exists for this upgrade"
-          exit 78
-        }
-        else {
-          echo "An existing PR for this upgrade does not exist"
-        }
+        $actionContinue = "${{ env.BranchName }}"
+        if ($actionContinue -eq 'true') {
+          $VerbosePreference = ($Env:INPUT_VERBOSE -eq "true") ? "Continue" : "SilentlyContinue"
+          
+          echo "::group::Checking for existing Pull Request"
+          
+          $ghRepoParts = "${{ github.repository }}".Split("/")
+          $pr = Get-PullRequest -OwnerName $ghRepoParts[0] -RepositoryName $ghRepoParts[1] -AccessToken ${{ inputs.github-token }} -BranchName ${{ env.BranchName }}
+          
+          if ($pr) {
+            echo "::error::A Pull Request already exists for this upgrade"
+            echo ("ActionContinue='false') >> $Env:GITHUB_ENV
+          }
+          else {
+            echo "An existing PR for this upgrade does not exist"
+          }
 
-        echo "::endgroup::"
+          echo "::endgroup::"
+        }        
       shell: pwsh
 
     - name: Push Changes
       run : |
-        if ($Env:INPUT_DISABLE_PUSH -eq "true") {
-          echo "::warning::Commit step is disabled. Quitting."
-          exit 78
-        }
-        
-        echo "::group::Pushing changes"
-        git -c "user.name=${{ inputs.git-bot-user }}" -c "user.email=${{ inputs.git-bot-email }}" push -u origin "${{ env.BranchName }}"
-        echo "::endgroup::"
+        $actionContinue = "${{ env.BranchName }}"
+        if ($actionContinue -eq 'true') {
+          if ($Env:INPUT_DISABLE_PUSH -eq "true") {
+            echo "::warning::Commit step is disabled. Quitting."
+            echo ("ActionContinue='false') >> $Env:GITHUB_ENV
+          }
+          else {
+            echo "::group::Pushing changes"
+            git -c "user.name=${{ inputs.git-bot-user }}" -c "user.email=${{ inputs.git-bot-email }}" push -u origin "${{ env.BranchName }}"
+            echo "::endgroup::"
+          }                
+        }        
       shell: pwsh
       
     - name: Creating pull request
       run : |
-        $VerbosePreference = ($Env:INPUT_VERBOSE -eq "true") ? "Continue" : "SilentlyContinue"
+        $actionContinue = "${{ env.BranchName }}"
+        if ($actionContinue -eq 'true') {
+          $VerbosePreference = ($Env:INPUT_VERBOSE -eq "true") ? "Continue" : "SilentlyContinue"
 
-        if ($Env:INPUT_DISABLE_PULL_REQUEST -eq "true") {
-          echo "::warning::Pull request step is disabled. Quitting."
-          exit 78
-        }
-        echo "::group::Creating Pull Request"
-        $ghRepoParts = "${{ github.repository }}".Split("/")
-        $pr = New-PullRequest -OwnerName $ghRepoParts[0] -RepositoryName $ghRepoParts[1] -AccessToken ${{ inputs.github-token }} -SourceVersion ${{ env.CurrentVersion }} -PackageVersion ${{ env.ActualVersion }} -PackageName ${{ inputs.package-name }} -BranchName ${{ env.BranchName }}
-        echo "::endgroup::"
+          if ($Env:INPUT_DISABLE_PULL_REQUEST -eq "true") {
+            echo "::warning::Pull request step is disabled. Quitting."
+            echo ("ActionContinue='false') >> $Env:GITHUB_ENV
+          }
+          else {
+            echo "::group::Creating Pull Request"
+            $ghRepoParts = "${{ github.repository }}".Split("/")
+            $pr = New-PullRequest -OwnerName $ghRepoParts[0] -RepositoryName $ghRepoParts[1] -AccessToken ${{ inputs.github-token }} -SourceVersion ${{ env.CurrentVersion }} -PackageVersion ${{ env.ActualVersion }} -PackageName ${{ inputs.package-name }} -BranchName ${{ env.BranchName }}
+            echo "::endgroup::"
+          }          
+        }        
       shell: pwsh
